import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Open_Sans, Inter } from "next/font/google";
import AppProviders from "@/providers";
import "./globals.css";
import Header from "@/components/navigation/header";
import { SidebarInset } from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";
import { AppSidebar } from "@/components/navigation/sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});
const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});
const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Java Flow",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.variable} font-geist antialiased overflow-x-hidden`}
            >
                <AppProviders>
                    <AppSidebar />
                    <SidebarInset>
                        <Header />
                        <Separator />
                        <main className="flex flex-1 max-w-screen flex-col gap-4 p-0 pt-0 overflow-x-hidden">
                            {children}
                        </main>
                    </SidebarInset>
                </AppProviders>
            </body>
        </html>
    );
}
